### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by r76941156** [smart-on-fhir/sample-apps#1]
Hello,

I followed the steps to install and setup the apps. But, when I ran any of them, I always got below error message:

GET /?error=invalid_scope&error_description=Invalid%20scope.....

Then, I can't see any outcomes. Do you know how to fix it? Thanks.

Sanders

**Comment by toddprater** [comment]
You don't say which sample app(s) you're trying to run, but I got the same error when running the medications app. In order to get it to work, the scope in launch.html needs to match exactly what's in the sandbox app config. When you create the sandbox app, you'll see one of the configuration options named 'scopes' which has a default value of `launch patient/*.* openid profile`. You need to change this to match what's in launch.html, i.e., just `patient/*.read`. This got me up and running, anyway.

**Comment by vlad-ignatov** [comment]
We are not using the old sandbox anymore. Registering an app or modifying it's launch.html file is no longer necessary. Instead we use the launcher at https://launch.smarthealthit.org. All the README files have been updated. I hope that clears the confusion.
